<a href="https://colab.research.google.com/github/asithishantha/ANN-on-Churn-Modeling-Dataset-for-a-Bank_using_Keras/blob/main/ANN_on_Churn_Modeling_Dataset_for_a_Bank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#So in this dataset we would be dealing with Churn Modeling i.e. we would be writing a Artificial Neural Network
#to find out reasons as to why and which customers are actually leaving the bank and their dependencies on one another.
#This is a classification problem 0-1 classification(1 if Leaves 0 if customer stays)
#We might use Theano or Tensorflow but the thing is that these libraries require us to write most of the Ml code from
#scratch so instead we make use of Keras which enables us writing powerful Neural Networks with a few lines of code
#Keras runs on Theano and Tensorflow and you can think it of as a Sklearn for Deep Learning
# Artificial Neural Network

# Part 1 - Data Preprocessing


# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
dataset=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [5]:
#Looking at the features we can see that row no.,name will have no relation with a customer with leaving the bank
#so we drop them from X which contains the features Indexes from 3 to 12


X = dataset.iloc[:, 3:13].values

In [6]:
#We store the Dependent value/predicted value in y by storing the 13th index in the variable y
y = dataset.iloc[:, 13].values

In [7]:
#Printing out the values of X --> Which contains the features
#                           y --> Which contains the target variable
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [8]:
# Encoding categorical data
# Now we encode the string values in the features to numerical values
# The only 2 values are Gender and Region which need to converted into numerical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [9]:
labelencoder_X_1 = LabelEncoder()#creating label encoder object no. 1 to encode region name(index 1 in features)

In [10]:
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])#encoding region from string to just 3 no.s 0,1,2 respectively

In [11]:
labelencoder_X_2 = LabelEncoder()#creating label encoder object no. 2 to encode Gender name(index 2 in features)

In [12]:
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2]) #encoding Gender from string to just 2 no.s 0,1(male,female) respectively

In [13]:
# #Now creating Dummy variables
# onehotencoder = OneHotEncoder(categorical_features = [1])
# X = onehotencoder.fit_transform(X).toarray()
# X = X[:, 1:]

#Encode Country Column
labelencoder_X = LabelEncoder()
X[:,0] = labelencoder_X.fit_transform(X[:,0])
ct = ColumnTransformer([("Country", OneHotEncoder(), [0])], remainder = 'passthrough')
X = ct.fit_transform(X)

In [14]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [15]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler(with_mean=False)
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)




In [16]:
# Part 2 - Now let's make the ANN!

In [17]:
'''
Listing out the steps involved in training the ANN with Stochastic Gradient Descent
1)Randomly initialize the weights to small numbers close to 0(But not 0)
2)Input the 1st observation of your dataset in the Input Layer, each Feature in one Input Node
3)Forward-Propagation from Left to Right, the neurons are activated in a way that the impact of each neuron's activation
is limited by the weights.Propagate the activations until getting the predicted result y.
4)Compare the predicted result with the actual result. Measure the generated error.
5)Back-Propagation: From Right to Left, Error is back  propagated.Update the weights according to how much they are
responsible for the error.The Learning Rate tells us by how much such we update the weights.
6)Repeat Steps 1 to 5 and update the weights after each observation(Reinforcement Learning).
Or: Repeat Steps 1 to 5 but update the weights only after a batch of observations(Batch Learning)  
7)When the whole training set is passed through the ANN.That completes an Epoch. Redo more Epochs


'''

"\nListing out the steps involved in training the ANN with Stochastic Gradient Descent\n1)Randomly initialize the weights to small numbers close to 0(But not 0)\n2)Input the 1st observation of your dataset in the Input Layer, each Feature in one Input Node\n3)Forward-Propagation from Left to Right, the neurons are activated in a way that the impact of each neuron's activation\nis limited by the weights.Propagate the activations until getting the predicted result y.\n4)Compare the predicted result with the actual result. Measure the generated error.\n5)Back-Propagation: From Right to Left, Error is back  propagated.Update the weights according to how much they are\nresponsible for the error.The Learning Rate tells us by how much such we update the weights.\n6)Repeat Steps 1 to 5 and update the weights after each observation(Reinforcement Learning).\nOr: Repeat Steps 1 to 5 but update the weights only after a batch of observations(Batch Learning)  \n7)When the whole training set is passe

In [18]:
# Importing the Keras libraries and packages

# from tensorflow.keras.models import Sequential

# from tensorflow.keras.layers import Dense,Dropout,Activation, Flatten, Conv2D, MaxPooling2D

!pip install tensorflow==2.0.0



#To randomly initialize the weights to small numbers close to 0(But not 0)

     |████████████████████████████████| 86.3 MB 37 kB/s 
     |████████████████████████████████| 449 kB 47.7 MB/s 
     |████████████████████████████████| 50 kB 5.6 MB/s 
     |████████████████████████████████| 3.8 MB 46.5 MB/s 
  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7553 sha256=b02bef6edcf6699c291db2c7650a6e956a503d1776f5484de6b00d7e107f5142
  Stored in directory: /root/.cache/pip/wheels/21/7f/02/420f32a803f7d0967b48dd823da3f558c5166991bfd204eef3
Successfully built gast
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.5.0
    Uninstalling tensorflow-estimator-2.5.0:
      Successfully uninstalled tensorflow-estimator-2.5.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.5.0
    Uninstalling tensorboard-2.5.0:
      Successfully uninstalled tensorboard-2.5.0
  Attempting uninstall: gast
    Found existing installation: gast 0.4.0
    Uninstalling gast-0.4.0:
      Success

In [19]:
import tensorflow as tf 
tf.__version__

import tensorflow as tf
mnist = tf.keras.datasets.mnist

(X_train, y_train),(X_test, y_test) = mnist.load_data()
X_train, X_test = X_train / 255.0, X_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='sigmoid')
  # tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, batch_size = 10,epochs=100)
model.evaluate(X_test, y_test)

11493376/11490434 [==============================] - 0s 0us/step
Train on 60000 samples
Epoch 1/100
60000/60000 [==============================] - 15s 249us/sample - loss: 0.2848 - accuracy: 0.9163
Epoch 2/100
60000/60000 [==============================] - 14s 238us/sample - loss: 0.1402 - accuracy: 0.9581
Epoch 3/100
60000/60000 [==============================] - 14s 239us/sample - loss: 0.1098 - accuracy: 0.9660
Epoch 4/100
60000/60000 [==============================] - 14s 237us/sample - loss: 0.0938 - accuracy: 0.9707
Epoch 5/100
60000/60000 [==============================] - 14s 235us/sample - loss: 0.0815 - accuracy: 0.9739
Epoch 6/100
60000/60000 [==============================] - 14s 240us/sample - loss: 0.0730 - accuracy: 0.9763
Epoch 7/100
60000/60000 [==============================] - 14s 236us/sample - loss: 0.0673 - accuracy: 0.9783
Epoch 8/100
60000/60000 [==============================] - 14s 241us/sample - loss: 0.0605 - accuracy: 0.9808
Epoch 9/100
60000/60000 [=======

[0.1306372106235649, 0.9773]

In [29]:
from sklearn.metrics import multilabel_confusion_matrix, classification_report, confusion_matrix
model.summary()

# Y_pred = np.argmax(model.predict(X_test),axis=1)
# print('Confusion Matrix')
# print(multilabel_confusion_matrix(y_test, Y_pred))
# print('Classification Report')


y_test_arg=np.argmax(model.predict(X_test),axis=1)
Y_pred = np.argmax(model.predict(X_test),axis=1)
print('Confusion Matrix')
print(confusion_matrix(y_test_arg, Y_pred))

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________
Confusion Matrix
[[1009    0    0    0    0    0    0    0    0    0]
 [   0 1126    0    0    0    0    0    0    0    0]
 [   0    0 1033    0    0    0    0    0    0    0]
 [   0    0    0 1024    0    0    0    0    0    0]
 [   0    0    0   

In [30]:
accuracy=(1550+175)/2000   #Obtained from Confusion Matrix
print(accuracy)

0.8625
